name: CI for Angular
on: push
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install pnpm 9.15.5
        run: |
          corepack enable
          corepack prepare pnpm@9.15.5 --activate
          echo "PNPM_HOME=$HOME/.local/share/pnpm" >> $GITHUB_ENV
          echo "PATH=$HOME/.local/share/pnpm:$PATH" >> $GITHUB_ENV
          pnpm --version

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm test -- --no-watch --code-coverage --browsers=ChromeHeadlessCI
